collective: 11ty
tiers:
  - tiers: '*'
    labels: ["oc-supporter"]
    message: "Hey <author>, thanks for supporting us on Open Collective!"
invitation: |
  Hey <author> :wave:,

  Thank you for opening an issue. We will get back to you as soon as we can.

  Also, check out our [Open Collective](https://opencollective.com/11ty) and consider backing us—every little bit helps!
