name: Feature request!
description: Enhancements. e.g. “I wish Eleventy did this.” Suggest an idea!
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request, please search for the feature in the existing issues. 

        ---

        Thank you for taking the time to file a feature request. To address this feature as fast as possible, we need some information.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
