name: Publish Canary Release to npm
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.name, 'Pre-release:') && github.event.release.isPrerelease
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish --provenance --access=public --tag=canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
