name: Remove cleanup label on issues after comment

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.comment.author_association != 'OWNER' &&
      github.event.comment.author_association != 'COLLABORATOR'
    steps:
      - name: Remove cleanup label on issues after comment
        uses: octokit/request-action@v2.x
        continue-on-error: true
        with:
          route: DELETE /repos/:repository/issues/:issue/labels/:label
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          label: cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}